project_id = "vzvnpjhbuwiorlylsugj"

[functions.translate]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.conversation]
verify_jwt = false